# Lab 02 : GPU demo

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Set the device variable to be either cuda or cpu

In [4]:
device = torch.device("cuda")

#device = torch.device("cpu")

print(device)

# torch.cuda.get_device_name(0)

cuda


AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

### Make a random tensor (by default the tensor is created on the CPU)

In [3]:
x=torch.rand(3,3)

print(x)

tensor([[0.4447, 0.6969, 0.1978],
        [0.2306, 0.2192, 0.5045],
        [0.6746, 0.6673, 0.7372]])


### Send the tensor to the device (which is going to be be the GPU if the device was set to be the GPU -- otherwise it will remain on the CPU)

In [11]:
x=x.to(device)

print(x)

tensor([[0.2126, 0.8232, 0.9466],
        [0.0370, 0.5176, 0.7032],
        [0.4544, 0.4457, 0.8515]])


### Make a one layer net class

In [12]:
class one_layer_net(nn.Module):

    def __init__(self, input_size, output_size):
        super(one_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, output_size , bias=False)
        
    def forward(self, x):
        scores = self.layer1(x)
        return scores

### Build the net

In [13]:
net=one_layer_net(5,2)

### Send all the weights of the network to the GPU

In [14]:
net = net.to(device)

### Ckeck that the matrix is indeed on the GPU

In [8]:
print(net.layer1.weight)

Parameter containing:
tensor([[-0.2646,  0.0491,  0.3317,  0.2717,  0.0483],
        [ 0.1272, -0.3401,  0.1400,  0.0687,  0.3442]], requires_grad=True)
